# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ep <- function(intercepts, coefficients, latent_positions, sender, recipient, current_covariates, interaction_pattern, using_coefficients) {
    .Call('CCAS_ep', PACKAGE = 'CCAS', intercepts, coefficients, latent_positions, sender, recipient, current_covariates, interaction_pattern, using_coefficients)
}

lsms <- function(unnormalized_discrete_distribution, seed) {
    .Call('CCAS_lsms', PACKAGE = 'CCAS', unnormalized_discrete_distribution, seed)
}

sotep <- function(edge_probabilities, tokens_in_document, current_token_topic_assignment, current_document_topic_counts, leave_out_current_token, topic_interaction_patterns, document_sender, document_recipient, leave_out_topic) {
    .Call('CCAS_sotep', PACKAGE = 'CCAS', edge_probabilities, tokens_in_document, current_token_topic_assignment, current_document_topic_counts, leave_out_current_token, topic_interaction_patterns, document_sender, document_recipient, leave_out_topic)
}

ppipp <- function(intercepts, coefficients, latent_positions, intercept_prior_mean, intercept_prior_variance, coefficient_prior_mean, coefficient_prior_variance, latent_position_prior_mean, latent_position_prior_variance, using_coefficients) {
    .Call('CCAS_ppipp', PACKAGE = 'CCAS', intercepts, coefficients, latent_positions, intercept_prior_mean, intercept_prior_variance, coefficient_prior_mean, coefficient_prior_variance, latent_position_prior_mean, latent_position_prior_variance, using_coefficients)
}

snipp <- function(intercepts, coefficients, latent_positions, intercept_proposal_variances, coefficient_proposal_variances, latent_position_proposal_variances, using_coefficients) {
    .Call('CCAS_snipp', PACKAGE = 'CCAS', intercepts, coefficients, latent_positions, intercept_proposal_variances, coefficient_proposal_variances, latent_position_proposal_variances, using_coefficients)
}

lsmc <- function(edge_probabilities, tokens_in_document, topic, current_token_topic_assignment, current_document_topic_counts, document_edge_values, topic_interaction_patterns, document_sender) {
    .Call('CCAS_lsmc', PACKAGE = 'CCAS', edge_probabilities, tokens_in_document, topic, current_token_topic_assignment, current_document_topic_counts, document_edge_values, topic_interaction_patterns, document_sender)
}

ldac <- function(tokens_in_document, current_token_topic_assignment, current_document_topic_counts, word_type_topic_counts, topic_token_counts, topic, current_word_type, alpha_m, beta_n, beta) {
    .Call('CCAS_ldac', PACKAGE = 'CCAS', tokens_in_document, current_token_topic_assignment, current_document_topic_counts, word_type_topic_counts, topic_token_counts, topic, current_word_type, alpha_m, beta_n, beta)
}

ustta <- function(edge_probabilities, tokens_in_document, current_token_topic_assignment, current_document_topic_counts, word_type_topic_counts, topic_token_counts, current_word_type, alpha_m, beta_n, document_edge_values, topic_interaction_patterns, document_sender, rand_num) {
    .Call('CCAS_ustta', PACKAGE = 'CCAS', edge_probabilities, tokens_in_document, current_token_topic_assignment, current_document_topic_counts, word_type_topic_counts, topic_token_counts, current_word_type, alpha_m, beta_n, document_edge_values, topic_interaction_patterns, document_sender, rand_num)
}

utta <- function(author_indexes, document_edge_matrix, topic_interaction_patterns, document_topic_counts, word_type_topic_counts, topic_token_counts, token_topic_assignments, token_word_types, intercepts, coefficients, latent_positions, covariates, alpha_m, beta_n, random_numbers, using_coefficients) {
    .Call('CCAS_utta', PACKAGE = 'CCAS', author_indexes, document_edge_matrix, topic_interaction_patterns, document_topic_counts, word_type_topic_counts, topic_token_counts, token_topic_assignments, token_word_types, intercepts, coefficients, latent_positions, covariates, alpha_m, beta_n, random_numbers, using_coefficients)
}

uipp <- function(author_indexes, document_edge_matrix, document_topic_counts, topic_interaction_patterns, intercepts, coefficients, latent_positions, covariates, using_coefficients, intercept_prior_mean, intercept_prior_variance, intercept_proposal_variances, coefficient_prior_mean, coefficient_prior_variance, coefficient_proposal_variances, latent_position_prior_mean, latent_position_prior_variance, latent_position_proposal_variances, random_number, edge_probabilities) {
    .Call('CCAS_uipp', PACKAGE = 'CCAS', author_indexes, document_edge_matrix, document_topic_counts, topic_interaction_patterns, intercepts, coefficients, latent_positions, covariates, using_coefficients, intercept_prior_mean, intercept_prior_variance, intercept_proposal_variances, coefficient_prior_mean, coefficient_prior_variance, coefficient_proposal_variances, latent_position_prior_mean, latent_position_prior_variance, latent_position_proposal_variances, random_number, edge_probabilities)
}

utipa <- function(author_indexes, document_edge_matrix, document_topic_counts, topic_interaction_patterns, intercepts, coefficients, latent_positions, covariates, using_coefficients, random_numbers, edge_probabilities) {
    .Call('CCAS_utipa', PACKAGE = 'CCAS', author_indexes, document_edge_matrix, document_topic_counts, topic_interaction_patterns, intercepts, coefficients, latent_positions, covariates, using_coefficients, random_numbers, edge_probabilities)
}

am <- function(intercept_proposal_variances, coefficient_proposal_variances, latent_position_proposal_variances, accept_rates, target_accept_rate, tollerance, update_size) {
    .Call('CCAS_am', PACKAGE = 'CCAS', intercept_proposal_variances, coefficient_proposal_variances, latent_position_proposal_variances, accept_rates, target_accept_rate, tollerance, update_size)
}

model_inference <- function(author_indexes, document_edge_matrix, document_topic_counts, topic_interaction_patterns, word_type_topic_counts, topic_token_counts, token_topic_assignments, token_word_types, intercepts, coefficients, latent_positions, covariates, alpha_m, beta_n, using_coefficients, intercept_prior_mean, intercept_prior_variance, intercept_proposal_variances, coefficient_prior_mean, coefficient_prior_variance, coefficient_proposal_variances, latent_position_prior_mean, latent_position_prior_variance, latent_position_proposal_variances, target_accept_rate, tollerance, update_size, seed, iterations, metropolis_iterations, total_number_of_tokens, iterations_before_t_i_p_updates, update_t_i_p_every_x_iterations, perform_adaptive_metropolis) {
    .Call('CCAS_model_inference', PACKAGE = 'CCAS', author_indexes, document_edge_matrix, document_topic_counts, topic_interaction_patterns, word_type_topic_counts, topic_token_counts, token_topic_assignments, token_word_types, intercepts, coefficients, latent_positions, covariates, alpha_m, beta_n, using_coefficients, intercept_prior_mean, intercept_prior_variance, intercept_proposal_variances, coefficient_prior_mean, coefficient_prior_variance, coefficient_proposal_variances, latent_position_prior_mean, latent_position_prior_variance, latent_position_proposal_variances, target_accept_rate, tollerance, update_size, seed, iterations, metropolis_iterations, total_number_of_tokens, iterations_before_t_i_p_updates, update_t_i_p_every_x_iterations, perform_adaptive_metropolis)
}

mjd_rdirichlet <- function(alpha_m) {
    .Call('CCAS_mjd_rdirichlet', PACKAGE = 'CCAS', alpha_m)
}

sttgp <- function(token_topic_assignments, token_word_types, alpha_m, beta_n, number_of_documents, resample_word_types, random_numbers) {
    .Call('CCAS_sttgp', PACKAGE = 'CCAS', token_topic_assignments, token_word_types, alpha_m, beta_n, number_of_documents, resample_word_types, random_numbers)
}

