# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ep <- function(intercepts, coefficients, latent_pos, sender, recipient, current_covariates, interaction_pattern, using_coefficients) {
    .Call('CCAS_ep', PACKAGE = 'CCAS', intercepts, coefficients, latent_pos, sender, recipient, current_covariates, interaction_pattern, using_coefficients)
}

lsms <- function(unnormalized_discrete_distribution, seed) {
    .Call('CCAS_lsms', PACKAGE = 'CCAS', unnormalized_discrete_distribution, seed)
}

