# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ep <- function(intercepts, coefficients, latent_pos, sender, recipient, current_covariates, interaction_pattern, using_coefficients) {
    .Call('CCAS_ep', PACKAGE = 'CCAS', intercepts, coefficients, latent_pos, sender, recipient, current_covariates, interaction_pattern, using_coefficients)
}

lsms <- function(unnormalized_discrete_distribution, seed) {
    .Call('CCAS_lsms', PACKAGE = 'CCAS', unnormalized_discrete_distribution, seed)
}

ppipp <- function(intercepts, coefficients, latent_pos, intercept_prior_mean, intercept_prior_variance, coefficient_prior_mean, coefficient_prior_variance, latent_position_prior_mean, latent_position_prior_variance, using_coefficients) {
    .Call('CCAS_ppipp', PACKAGE = 'CCAS', intercepts, coefficients, latent_pos, intercept_prior_mean, intercept_prior_variance, coefficient_prior_mean, coefficient_prior_variance, latent_position_prior_mean, latent_position_prior_variance, using_coefficients)
}

snipp <- function(intercepts, coefficients, latent_pos, intercept_prior_variance, coefficient_prior_variance, latent_position_prior_variance, using_coefficients) {
    .Call('CCAS_snipp', PACKAGE = 'CCAS', intercepts, coefficients, latent_pos, intercept_prior_variance, coefficient_prior_variance, latent_position_prior_variance, using_coefficients)
}

sotep <- function(edge_probs, tokens_in_document, current_token_topic_assignment, current_document_topic_counts, leave_out_current_token, topic_interaction_patterns, document_sender, document_recipient, leave_out_topic) {
    .Call('CCAS_sotep', PACKAGE = 'CCAS', edge_probs, tokens_in_document, current_token_topic_assignment, current_document_topic_counts, leave_out_current_token, topic_interaction_patterns, document_sender, document_recipient, leave_out_topic)
}

